version: "3.9"

services:
  app:
    build: ../../../..
    command: "true"
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS?"missing credentials"}:/tmp/.credentials
      - ../../content.json:/app/config/content.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/.credentials
      - APP_NAME
      - DATA_CONFIG
      - ORIGIN_CONFIG
      - PUBLIC_KEY_HEX_INTERNAL
      - PUBLIC_KEY_HEX_EXTERNAL
      - BUCKET_INTERNAL_ACCESS_KEY
      - BUCKET_INTERNAL_SECRET_KEY
      - BUCKET_EXTERNAL_ACCESS_KEY
      - BUCKET_EXTERNAL_SECRET_KEY
      - BUCKET_INTERNAL_INGEST
      - BUCKET_EXTERNAL_INGEST
      # for submitting results to bigquery, granted access via GCP primitives
      # instead of HMAC keys
      - BUCKET_INTERNAL_PRIVATE
      - BUCKET_PREFIX
      - DATASET
      - TABLE
      - BQ_REPLACE
      - CLOUDSDK_CORE_PROJECT
      - SUBMISSION_DATE
