#!/bin/bash

# Build each docker-compose service by changing directories

set -euo pipefail
cd "$(dirname "$0")/.."

pushd compose/ingest
docker-compose build
popd

pushd compose/server-a
docker-compose build
popd

pushd compose/server-b
docker-compose build
popd
