#!/bin/bash

# Delegate cleanup of buckets to the appropriate service account

set -euo pipefail
cd "$(dirname "$0")/.."

pushd compose/server-b
docker-compose run --rm app bin/cleanup
# keep the container around...

pushd ../../compose/server-a
docker-compose run --rm app bin/cleanup
docker-compose down
popd

docker-compose down
# unnecessary, but pop back into the root
popd
