#!/bin/bash

# Run cleanup scripts for each server

set -euo pipefail
cd "$(dirname "$0")/.."

pushd compose/server-b
docker-compose run --rm app bin/cleanup
# keep the container around since the network depends on server b

pushd ../../compose/server-a
docker-compose run --rm app bin/cleanup
docker-compose down
popd

docker-compose down
