#!/usr/bin/env bash

set -e

PROJECT=${PROJECT:-amiyaguchi-prio-processor-v4-1}

if [[ $(gcloud config get-value project) != "$PROJECT" ]]; then 
    echo "project is not set correctly; run 'gcloud config set project $PROJECT'"
    exit 1
fi

# work from the parent directory
cd "$(dirname "$0")/.."
output=.secrets
mkdir -p $output

function create_service_account {
    local project=$1
    local output=$2
    local name=$3
    gcloud iam service-accounts keys create "$output/$name-private-key.json" \
        --iam-account "$name@$project.iam.gserviceaccount.com"
}

create_service_account "$PROJECT" "$output" service-account-ingest
create_service_account "$PROJECT" "$output" service-account-a
create_service_account "$PROJECT" "$output" service-account-b
