#!/bin/bash

set -eou pipefail
set -x

# Parameters that are read through the environment
: ${N_DATA?}
: ${BATCH_ID?}
: ${SERVER_ID}
: ${SHARED_SECRET?}
: ${PRIVATE_KEY_HEX?}
: ${PUBLIC_KEY_HEX_INTERNAL?}
: ${PUBLIC_KEY_HEX_EXTERNAL?}

: ${MINIO_ACCESS_KEY?}
: ${MINIO_SECRET_KEY?}
: ${BUCKET_INTERNAL?}
: ${BUCKET_EXTERNAL?}

TARGET="minio"

mc config host add $TARGET http://minio:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY --api s3v4;

cd /tmp
mkdir -p raw
mkdir -p intermediate/internal/verify1
mkdir -p intermediate/internal/verify2
mkdir -p intermediate/internal/aggregate
mkdir -p processed


# Wait for a completed batch of data, signaled by the appearance of a _SUCCESS
# file.
#
# Arguments:
#   $1 - Absolute path to a file
function poll_for_data() {
    set +e
    max_retries=4
    retries=0
    backoff=2
    while ! mc stat $1 &>/dev/null; do
        sleep $backoff;
        ((backoff *= 2))
        ((retries++))
        if [[ "$retries" -gt "$max_retries" ]]; then
            echo "Reached the maximum number of retries."
            exit 1
        fi
    done
    set -e
}


# Poll for a success file and then copy the appropriate files locally
#
# Arguments:
#   $1 - Path relative to TARGET/BUCKET_INTERNAL
#
# Environment:
#   TARGET - The minio host
#   BUCKET_INTERNAL - The bucket pointing to this server's data
function fetch_input_blocked() {
    local input=$1
    local path=${TARGET}/${BUCKET_INTERNAL}/$input
    poll_for_data $path/_SUCCESS
    mc cp --recursive $path/ $input/
}


# Copy data generated by a processing step into the receiving bucket of the
# co-processing server. A _SUCCESS file is generated on a successful copy.
#
# Arguments:
#   $1 - relative path to output for a processing stage
#   $2 - relative path to the external bucket of the external server
#
# Environment:
#   TARGET - The minio host
#   BUCKET_EXTERNAL - The bucket of the external server
function send_output_external() {
    local output_internal=$1
    local output_external=$2
    mc cp --recursive $output_internal/ ${TARGET}/${BUCKET_EXTERNAL}/$output_external/
    touch _SUCCESS
    mc cp _SUCCESS ${TARGET}/${BUCKET_EXTERNAL}/$output_external/
}


# Copy local data to a remote bucket that is accessible to the current server.
#
# Arguments:
#   $1 - relative path to a folder containing data
#
# Environment:
#   TARGET - The minio host
#   BUCKET_INTERNAL - The bucket pointing to this server's data
function send_output_internal() {
    local output=$1
    mc cp --recursive $output/ ${TARGET}/${BUCKET_INTERNAL}/$output/
    touch _SUCCESS
    mc cp _SUCCESS ${TARGET}/${BUCKET_INTERNAL}/$output/
}


# List partitions that are ready for processing.
#
# Arguments:
#   $1 - relative path to a folder containing data
function list_partitions() {
    local input=$1
    find $input -type f -not -name "_SUCCESS" -printf "%f\n"
}


###########################################################
# verify1
###########################################################

input="raw"
output_internal="intermediate/internal/verify1"
output_external="intermediate/external/verify1"

fetch_input_blocked $input

for filename in $(list_partitions $input); do
    prio verify1 \
        --input $input/$filename \
        --output $output_internal

    jq -c '.' $output_internal/$filename
done

send_output_external $output_internal $output_external

###########################################################
# verify2
###########################################################

input_internal="intermediate/internal/verify1"
input_external="intermediate/external/verify1"
output_internal="intermediate/internal/verify2"
output_external="intermediate/external/verify2"

fetch_input_blocked $input_external

for filename in $(list_partitions $input_internal); do
    prio verify2 \
        --input $input/$filename \
        --input-internal $input_internal/$filename \
        --input-external $input_external/$filename \
        --output $output_internal

    jq -c '.' $output_internal/$filename
done

send_output_external $output_internal $output_external


###########################################################
# aggregate
###########################################################

input_internal="intermediate/internal/verify2"
input_external="intermediate/external/verify2"
output_internal="intermediate/internal/aggregate"
output_external="intermediate/external/aggregate"

fetch_input_blocked $input_external

for filename in $(list_partitions $input_internal); do
    prio aggregate \
        --input $input/$filename \
        --input-internal $input_internal/$filename \
        --input-external $input_external/$filename \
        --output $output_internal

    jq -c '.' $output_internal/$filename
done

send_output_external $output_internal $output_external

###########################################################
# publish
###########################################################

input_internal="intermediate/internal/aggregate"
input_external="intermediate/external/aggregate"
output="processed"

fetch_input_blocked $input_external

for filename in $(list_partitions $input_internal); do
    prio publish \
        --input-internal $input_internal/$filename \
        --input-external $input_external/$filename \
        --output $output

    jq -c '.' $output/$filename
done

send_output_internal $output
