version: "3.4"

services:
  app:
    image: mozilla/prio-processor:v3.0.0
    command: "true"
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS?"missing credentials"}:/tmp/.credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/.credentials
      - APP_NAME
      - DATA_CONFIG
      - ORIGIN_CONFIG
      - PUBLIC_KEY_HEX_INTERNAL
      - PUBLIC_KEY_HEX_EXTERNAL
      - BUCKET_INTERNAL_PRIVATE
      - BUCKET_EXTERNAL_PRIVATE
      - BUCKET_PREFIX
      - DATASET=telemetry
      - TABLE=content_blocking_dev
      - BQ_REPLACE=true
      # Set the default project for inserting rows
      - CLOUDSDK_CORE_PROJECT
      - SUBMISSION_DATE
