version: "3.9"

networks:
  testing-v4-gcloud-self-b_default:
    external: true

services:
  # https://docs.min.io/docs/minio-gateway-for-gcs.html
  gcs-gateway-ingest:
    image: minio/minio:latest
    command: gateway gcs ${CLOUDSDK_CORE_PROJECT}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS?"missing credentials"}:/tmp/.credentials
    ports:
      - 9001:9000
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/.credentials
      - MINIO_ROOT_USER=$BUCKET_INTERNAL_ACCESS_KEY
      - MINIO_ROOT_PASSWORD=$BUCKET_INTERNAL_SECRET_KEY

  app:
    build: ../../../..
    command: "true"
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS?"missing credentials"}:/tmp/.credentials
      - ../../content.json:/app/config/content.json
      - ../../../../bin:/app/bin
    networks:
      - default
      - testing-v4-gcloud-self-b_default
    depends_on:
      - gcs-gateway-ingest
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/.credentials
      - APP_NAME
      - DATA_CONFIG
      - ORIGIN_CONFIG
      - PUBLIC_KEY_HEX_INTERNAL
      - PUBLIC_KEY_HEX_EXTERNAL
      - BUCKET_INTERNAL_ACCESS_KEY
      - BUCKET_INTERNAL_SECRET_KEY
      - BUCKET_INTERNAL_ENDPOINT
      - BUCKET_EXTERNAL_ACCESS_KEY
      - BUCKET_EXTERNAL_SECRET_KEY
      - BUCKET_EXTERNAL_ENDPOINT
      - BUCKET_INTERNAL_INGEST
      - BUCKET_EXTERNAL_INGEST
      - BUCKET_INTERNAL_PRIVATE
      - BUCKET_PREFIX
      - DATASET
      - TABLE
      - BQ_REPLACE
      - CLOUDSDK_CORE_PROJECT
      - SUBMISSION_DATE
