#!/bin/bash

if gcloud compute --project=$PROJECT instances describe --zone $ZONE $COMPUTE_INSTANCE_NAME &>/dev/null; then
  gcloud compute --project=$PROJECT instances delete $COMPUTE_INSTANCE_NAME
fi

if gcloud --project $PROJECT iam service-accounts describe $COMPUTE_SERVICE_ACCOUNT@$PROJECT.iam.gserviceaccount.com &>/dev/null; then
  input "Deleting compute service account"
  gcloud --project=$PROJECT iam service-accounts delete $COMPUTE_SERVICE_ACCOUNT@$PROJECT.iam.gserviceaccount.com
fi

if gsutil ls $BUCKET/ &>/dev/null; then
  input "Deleting gcs bucket"
  gsutil rm -r $BUCKET
fi
