#!/bin/bash

set -eou pipefail

input() {
  echo
  set +x
  echo "${1}... (RET to continue)" && read -r
  set -x
}
export -f input

export PROJECT="${PROJECT:-$USER-sandbox-demo}"
export SHARED_PROJECT=moz-fx-data-shar-nonprod-efed
export COMPUTE_INSTANCE_NAME=instance-1
export BUCKET=gs://$PROJECT
export COMPUTE_SERVICE_ACCOUNT=demo-service-account
export ZONE=us-west1-a
echo "Project ID is ${PROJECT}"
[[ $(gcloud config get-value project 2>/dev/null) == "$PROJECT" ]] || gcloud config set project $PROJECT

SCRIPT="$(dirname ${0})/${1}"
if [[ -z "$1" ]] || ! [[ -f "$SCRIPT" ]]; then
  echo "usage: ${0} ACTION"
  echo "See README.md for details"
  exit 1
fi

$SCRIPT
