#!/bin/bash

# Generate a markdown page to serve as markdown documentation and a diffing
# mechanism between revisions of the CLI.
#
# Usage:
#   pip install .
#   ./scripts/print-cli-help > docs/cli-help.md
#

set -euo pipefail

function md_fence() {
    echo '```bash'
    echo "${1}"
    echo '```'
}

function command_help() {
    local cmd=$1
    echo "## ${cmd} help"
    echo ""
    md_fence "$($cmd --help)"

    commands=$($cmd --help | sed "1,/Commands:/d" | grep "^  \w" | awk '{print $1}')
    for command in ${commands}; do
        echo ""
        echo "### \`$cmd ${command}\`"
        echo ""
        md_fence "$($cmd "${command}" --help)"
    done
}

cat <<EOF
# Command Line Reference

$(command_help prio)

$(command_help prio-spark)

$(command_help prio-processor)
EOF
