#!/usr/bin/env python3

import json
import os
import sys

from pathlib import Path
from os import environ
from subprocess import run
from typing import Generator, Union


def iter_data(path: Union[Path, str]) -> Generator[str, str, int]:
    """Iterate over data in the directory that belongs to prio pings."""
    p = Path(path)
    for item in p.iterdir():
        # {batch_id: str}-{shard_id: int}.ndjson
        if not item.name.startswith("content.blocking"):
            continue
        filename = item.name
        batch_id = filename[: filename.rfind(".")]
        n_data = 2046 if int(batch_id[-1]) == 0 else 441
        yield filename, batch_id, n_data


def process_raw(path: Union[Path, str]):
    """Trigger the integration script using the data in the raw folder"""
    for filename, batch_id, n_data in iter_data(path):
        batch_config = {
            "FILENAME": filename,
            "BATCH_ID": batch_id,
            "N_DATA": str(n_data),
        }
        env = {**environ, **batch_config}
        run("scripts/test-cli-integration", shell=True, env=env)


def map_processed(path: Union[Path, str]) -> dict:
    """Map the aggregated bitvector to the origins."""
    origins = json.loads(run("scripts/download-mapping", capture_output=True).stdout)
    p = Path(path)
    results = {}
    for filename, batch_id, n_data in iter_data(p):
        with open(p.joinpath(filename)) as f:
            data = json.load(f)
        # find the index into the origins mapping
        i = int(batch_id[-1])
        mapping = origins[i * 2046 : (i + 1) * 2046]
        results[batch_id] = {k: v for k, v in zip(mapping, data) if v}
    return results


def test_input_counts(expected: Path, result: dict):
    """Test the resulting aggregates against a tsv of [origin, counts]."""
    expected_data = {}
    with expected.open() as f:
        for line in f.readlines():
            k, v = line.split()
            expected_data[k] = int(v)

    left = set(expected_data.items())
    right = set(result.items())
    diff = left ^ right
    if diff:
        print(f"Unexpected difference: {diff}")
    else:
        print("No differences found. Success!")


def check_environment():
    """Check that the keys are set in the environment."""
    keys = {
        "SERVER_A_PUBLIC_KEY",
        "SERVER_B_PUBLIC_KEY",
        "SERVER_A_PRIVATE_KEY",
        "SERVER_B_PRIVATE_KEY",
    }
    unset_keys = keys - set(environ.keys())
    if unset_keys:
        print("The following environment variables must be set:")
        for key in unset_keys:
            print(key)
        sys.exit()


def main():
    root = Path(__file__).parent.parent
    working = root / "working"

    os.chdir(root)
    check_environment()
    process_raw(working / "server_a" / "raw")
    data = map_processed(working / "server_a" / "processed")

    test_expected = False
    if test_expected:
        test_input = root / "data" / "2019-05-15_test_ping_input_counts.txt"
        result = {
            **data["content.blocking_blocked_TESTONLY-0"],
            **data["content.blocking_blocked_TESTONLY-1"],
        }
        test_input_counts(test_input, result)

    print(json.dumps(data))


if __name__ == "__main__":
    main()
