#!/bin/bash

set -eou pipefail
set -x

cd "$(dirname "$0")/.."

key_a=$(prio keygen)
key_b=$(prio keygen)
shared=$(prio shared-seed)

###########################################################
# encode-shares
###########################################################

mkdir -p working/client

cat << EOF > working/client/data.ndjson
[1, 0, 0]
[1, 1, 0]
[1, 1, 1]
EOF

python -m prio encode-shares \
    --n-data 3 \
    --batch-id test \
    --public-key-internal $(jq -r ".public_key" <<< $key_a) \
    --public-key-external $(jq -r ".public_key" <<< $key_b) \
    --input working/client/data.ndjson \
    --output-A working/server_a/raw/ \
    --output-B working/server_b/raw/

###########################################################
# verify1
###########################################################

python -m prio verify1 \
    --n-data 3 \
    --batch-id test \
    --server-id A \
    --private-key $(jq -r ".private_key" <<< $key_a) \
    --shared-secret $shared \
    --public-key-internal $(jq -r ".public_key" <<< $key_a) \
    --public-key-external $(jq -r ".public_key" <<< $key_b) \
    --input working/server_a/raw/data.ndjson \
    --output working/server_a/intermediate/internal/verify1

cp \
    working/server_a/intermediate/internal/verify1/data.ndjson \
    working/server_b/intermediate/external/verify1/

python -m prio verify1 \
    --n-data 3 \
    --batch-id test \
    --server-id B \
    --private-key $(jq -r ".private_key" <<< $key_b) \
    --shared-secret $shared \
    --public-key-internal $(jq -r ".public_key" <<< $key_b) \
    --public-key-external $(jq -r ".public_key" <<< $key_a) \
    --input working/server_b/raw/data.ndjson \
    --output working/server_b/intermediate/internal/verify1

cp \
    working/server_b/intermediate/internal/verify1/data.ndjson \
    working/server_a/intermediate/external/verify1/
