#!/bin/bash

set -eou pipefail
set -x

cd "$(dirname "$0")/.."
scripts/create-folder

key_a=$(prio keygen)
key_b=$(prio keygen)
shared=$(prio shared-seed)

N_DATA=3
BATCH_ID="test"
SHARED_SECRET=$shared

SERVER_A_PUBLIC_KEY=$(jq -r ".public_key" <<< $key_a)
SERVER_B_PUBLIC_KEY=$(jq -r ".public_key" <<< $key_b)

SERVER_A_PRIVATE_KEY=$(jq -r ".private_key" <<< $key_a)
SERVER_B_PRIVATE_KEY=$(jq -r ".private_key" <<< $key_b)

CLIENT_BUCKET="working/client"
SERVER_A_BUCKET="working/server_a"
SERVER_B_BUCKET="working/server_b"

###########################################################
# encode-shares
###########################################################

mkdir -p ${CLIENT_BUCKET}

cat << EOF > ${CLIENT_BUCKET}/data.ndjson
[1, 0, 0]
[1, 1, 0]
[1, 1, 1]
EOF

jq -c '.' ${CLIENT_BUCKET}/data.ndjson

python3 -m prio encode-shares \
    --n-data ${N_DATA} \
    --batch-id ${BATCH_ID} \
    --public-key-hex-internal ${SERVER_A_PUBLIC_KEY} \
    --public-key-hex-external ${SERVER_B_PUBLIC_KEY} \
    --input working/client/data.ndjson \
    --output-A ${SERVER_A_BUCKET}/raw/ \
    --output-B ${SERVER_B_BUCKET}/raw/

jq -c '.' ${SERVER_A_BUCKET}/raw/data.ndjson
jq -c '.' ${SERVER_B_BUCKET}/raw/data.ndjson

###########################################################
# verify1
###########################################################

python3 -m prio verify1 \
    --n-data ${N_DATA} \
    --batch-id ${BATCH_ID} \
    --server-id A \
    --private-key-hex ${SERVER_A_PRIVATE_KEY} \
    --shared-secret $shared \
    --public-key-hex-internal ${SERVER_A_PUBLIC_KEY} \
    --public-key-hex-external ${SERVER_B_PUBLIC_KEY} \
    --input ${SERVER_A_BUCKET}/raw/data.ndjson \
    --output ${SERVER_A_BUCKET}/intermediate/internal/verify1

jq -c '.' ${SERVER_A_BUCKET}/intermediate/internal/verify1/data.ndjson

cp \
    ${SERVER_A_BUCKET}/intermediate/internal/verify1/data.ndjson \
    ${SERVER_B_BUCKET}/intermediate/external/verify1/

python3 -m prio verify1 \
    --n-data ${N_DATA} \
    --batch-id ${BATCH_ID} \
    --server-id B \
    --private-key-hex ${SERVER_B_PRIVATE_KEY} \
    --shared-secret $shared \
    --public-key-hex-internal ${SERVER_B_PUBLIC_KEY} \
    --public-key-hex-external ${SERVER_A_PUBLIC_KEY} \
    --input ${SERVER_B_BUCKET}/raw/data.ndjson \
    --output ${SERVER_B_BUCKET}/intermediate/internal/verify1

jq -c '.' ${SERVER_B_BUCKET}/intermediate/internal/verify1/data.ndjson

cp \
    ${SERVER_B_BUCKET}/intermediate/internal/verify1/data.ndjson \
    ${SERVER_A_BUCKET}/intermediate/external/verify1/

###########################################################
# verify2
###########################################################

python3 -m prio verify2 \
    --n-data ${N_DATA} \
    --batch-id ${BATCH_ID} \
    --server-id A \
    --private-key-hex ${SERVER_A_PRIVATE_KEY} \
    --shared-secret $shared \
    --public-key-hex-internal ${SERVER_A_PUBLIC_KEY} \
    --public-key-hex-external ${SERVER_B_PUBLIC_KEY} \
    --input ${SERVER_A_BUCKET}/raw/data.ndjson \
    --input-internal ${SERVER_A_BUCKET}/intermediate/internal/verify1/data.ndjson \
    --input-external ${SERVER_A_BUCKET}/intermediate/external/verify1/data.ndjson \
    --output ${SERVER_A_BUCKET}/intermediate/internal/verify2/ \

jq -c '.' ${SERVER_A_BUCKET}/intermediate/internal/verify2/data.ndjson

cp \
    ${SERVER_A_BUCKET}/intermediate/internal/verify2/data.ndjson \
    ${SERVER_B_BUCKET}/intermediate/external/verify2/

python3 -m prio verify2 \
    --n-data ${N_DATA} \
    --batch-id ${BATCH_ID} \
    --server-id B \
    --private-key-hex ${SERVER_B_PRIVATE_KEY} \
    --shared-secret $shared \
    --public-key-hex-internal ${SERVER_B_PUBLIC_KEY} \
    --public-key-hex-external ${SERVER_A_PUBLIC_KEY} \
    --input ${SERVER_B_BUCKET}/raw/data.ndjson \
    --input-internal ${SERVER_B_BUCKET}/intermediate/internal/verify1/data.ndjson \
    --input-external ${SERVER_B_BUCKET}/intermediate/external/verify1/data.ndjson \
    --output ${SERVER_B_BUCKET}/intermediate/internal/verify2/ \

jq -c '.' ${SERVER_B_BUCKET}/intermediate/internal/verify2/data.ndjson

cp \
    ${SERVER_B_BUCKET}/intermediate/internal/verify2/data.ndjson \
    ${SERVER_A_BUCKET}/intermediate/external/verify2/

###########################################################
# aggregate
###########################################################

python3 -m prio aggregate \
    --n-data ${N_DATA} \
    --batch-id ${BATCH_ID} \
    --server-id A \
    --private-key-hex ${SERVER_A_PRIVATE_KEY} \
    --shared-secret $shared \
    --public-key-hex-internal ${SERVER_A_PUBLIC_KEY} \
    --public-key-hex-external ${SERVER_B_PUBLIC_KEY} \
    --input ${SERVER_A_BUCKET}/raw/data.ndjson \
    --input-internal ${SERVER_A_BUCKET}/intermediate/internal/verify2/data.ndjson \
    --input-external ${SERVER_A_BUCKET}/intermediate/external/verify2/data.ndjson \
    --output ${SERVER_A_BUCKET}/intermediate/internal/aggregate/

jq -c '.' ${SERVER_A_BUCKET}/intermediate/internal/aggregate/data.ndjson

cp \
    ${SERVER_A_BUCKET}/intermediate/internal/aggregate/data.ndjson \
    ${SERVER_B_BUCKET}/intermediate/external/aggregate/

python3 -m prio aggregate \
    --n-data ${N_DATA} \
    --batch-id ${BATCH_ID} \
    --server-id B \
    --private-key-hex ${SERVER_B_PRIVATE_KEY} \
    --shared-secret $shared \
    --public-key-hex-internal ${SERVER_B_PUBLIC_KEY} \
    --public-key-hex-external ${SERVER_A_PUBLIC_KEY} \
    --input ${SERVER_B_BUCKET}/raw/data.ndjson \
    --input-internal ${SERVER_B_BUCKET}/intermediate/internal/verify2/data.ndjson \
    --input-external ${SERVER_B_BUCKET}/intermediate/external/verify2/data.ndjson \
    --output ${SERVER_B_BUCKET}/intermediate/internal/aggregate/ \

jq -c '.' ${SERVER_B_BUCKET}/intermediate/internal/verify2/data.ndjson

cp \
    ${SERVER_B_BUCKET}/intermediate/internal/aggregate/data.ndjson \
    ${SERVER_A_BUCKET}/intermediate/external/aggregate/

###########################################################
# publish
###########################################################

python3 -m prio publish \
    --n-data ${N_DATA} \
    --batch-id ${BATCH_ID} \
    --server-id A \
    --private-key-hex ${SERVER_A_PRIVATE_KEY} \
    --shared-secret $shared \
    --public-key-hex-internal ${SERVER_A_PUBLIC_KEY} \
    --public-key-hex-external ${SERVER_B_PUBLIC_KEY} \
    --input-internal ${SERVER_A_BUCKET}/intermediate/internal/aggregate/data.ndjson \
    --input-external ${SERVER_A_BUCKET}/intermediate/external/aggregate/data.ndjson \
    --output ${SERVER_A_BUCKET}/processed/

jq -c '.' ${SERVER_A_BUCKET}/processed/data.ndjson

python3 -m prio publish \
    --n-data ${N_DATA} \
    --batch-id ${BATCH_ID} \
    --server-id B \
    --private-key-hex ${SERVER_B_PRIVATE_KEY} \
    --shared-secret $shared \
    --public-key-hex-internal ${SERVER_B_PUBLIC_KEY} \
    --public-key-hex-external ${SERVER_A_PUBLIC_KEY} \
    --input-internal ${SERVER_B_BUCKET}/intermediate/internal/aggregate/data.ndjson \
    --input-external ${SERVER_B_BUCKET}/intermediate/external/aggregate/data.ndjson \
    --output ${SERVER_B_BUCKET}/processed/

jq -c '.' ${SERVER_B_BUCKET}/processed/data.ndjson
