version: "3.9"

services:
  minio-b:
    image: minio/minio:latest
    command: server /data
    ports:
      - 9004:9000
    environment:
      - MINIO_ACCESS_KEY=$BUCKET_INTERNAL_ACCESS_KEY
      - MINIO_SECRET_KEY=$BUCKET_INTERNAL_SECRET_KEY

  # This is run to set up policies on the buckets
  minio-bootstrap:
    build: ../../../..
    depends_on:
      - minio-b
    working_dir: /root
    command: bash bootstrap.sh
    volumes:
      - .:/root/
    environment:
      - BUCKET_INTERNAL_ACCESS_KEY
      - BUCKET_INTERNAL_SECRET_KEY
      - BUCKET_INTERNAL_ENDPOINT

  # https://docs.min.io/docs/minio-gateway-for-gcs.html
  gateway-b:
    image: minio/minio:latest
    command: gateway gcs
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS?"missing credentials"}:/tmp/.credentials
    ports:
      - 9003:9000
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/.credentials
      - MINIO_ROOT_USER=$BUCKET_INTERNAL_ACCESS_KEY
      - MINIO_ROOT_PASSWORD=$BUCKET_INTERNAL_SECRET_KEY

  app:
    build: ../../../..
    working_dir: /app
    command: bin/process
    volumes:
      - ../../content.json:/app/config/content.json
      - ../../../../bin:/app/bin
    depends_on:
      - gateway-b
      - minio-b
      - minio-bootstrap
    environment:
      - APP_NAME
      - DATA_CONFIG
      - SERVER_ID
      - SHARED_SECRET
      - PRIVATE_KEY_HEX
      - PUBLIC_KEY_HEX_INTERNAL
      - PUBLIC_KEY_HEX_EXTERNAL
      - BUCKET_INTERNAL_ACCESS_KEY
      - BUCKET_INTERNAL_SECRET_KEY
      - BUCKET_INTERNAL_ENDPOINT
      - BUCKET_EXTERNAL_ACCESS_KEY
      - BUCKET_EXTERNAL_SECRET_KEY
      - BUCKET_EXTERNAL_ENDPOINT
      - BUCKET_INTERNAL_INGEST
      - BUCKET_INTERNAL_PRIVATE
      - BUCKET_INTERNAL_SHARED
      - BUCKET_EXTERNAL_SHARED
      - BUCKET_PREFIX
      - SUBMISSION_DATE
