version: "3.4"

services:
  app:
    image: mozilla/prio-processor:v3.0.0
    working_dir: /app
    command: bin/process
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS?"missing credentials"}:/tmp/.credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/.credentials
      - APP_NAME
      - DATA_CONFIG
      - SERVER_ID
      - SHARED_SECRET
      - PRIVATE_KEY_HEX
      - PUBLIC_KEY_HEX_INTERNAL
      - PUBLIC_KEY_HEX_EXTERNAL
      - BUCKET_INTERNAL_PRIVATE
      - BUCKET_INTERNAL_SHARED
      - BUCKET_EXTERNAL_SHARED
      - BUCKET_PREFIX
      - SUBMISSION_DATE
